// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqmuhsyngnvmurqyorvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxbXVoc3luZ252bXVycXlvcnZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDMzNjMsImV4cCI6MjA2ODUxOTM2M30.RfYxIwtAvxv8Fkq9Dc68GzVFG79_vjCrTZEdDM1PsMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});